name:                brainscrambler
version:             0.1.0.0
github:              "kana-sama/brainscrambler"
license:             BSD3
author:              "Andrei Krasnabayeu"
maintainer:          "andrew4chrome@gmail.com"
copyright:           "2018 Andrei Krasnabayeu"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/kana-sama/brainscrambler#readme>

dependencies:
- base >= 4.7 && < 5
- universum

default-extensions:
- DeriveFoldable
- DeriveFunctor
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- OverloadedStrings
- RankNTypes
- RecordWildCards
- TemplateHaskell
- TupleSections
- TypeOperators

library:
  source-dirs: src
  dependencies:
  - containers
  - free
  - megaparsec
  - microlens-platform
  - mtl

tests:
  brainscrambler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brainscrambler
    - free
    - hspec
    - hspec-megaparsec
